// Mocks generated by Mockito 5.0.8 from annotations
// in posts_flutter/test/data/repositories/post_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:posts_flutter/data/models/posts.dart' as _i2;
import 'package:posts_flutter/data/remote/post_data_source.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakePosts extends _i1.Fake implements _i2.Posts {}

/// A class which mocks [PostDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostDataSource extends _i1.Mock implements _i3.PostDataSource {
  MockPostDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Posts> getPosts() =>
      (super.noSuchMethod(Invocation.method(#getPosts, []),
              returnValue: Future<_i2.Posts>.value(_FakePosts()))
          as _i4.Future<_i2.Posts>);
}
