// Mocks generated by Mockito 5.0.8 from annotations
// in posts_flutter/test/controllers/posts_controller/posts_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:posts_flutter/data/exceptions/get_posts_exception.dart' as _i6;
import 'package:posts_flutter/data/models/posts.dart' as _i5;
import 'package:posts_flutter/data/repositories/post_repository.dart' as _i3;
import 'package:posts_flutter/utils/result/result.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResult<T, U> extends _i1.Fake implements _i2.Result<T, U> {}

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i3.PostRepository {
  MockPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.Posts, _i6.GetPostsException>> getPosts() =>
      (super.noSuchMethod(Invocation.method(#getPosts, []),
              returnValue:
                  Future<_i2.Result<_i5.Posts, _i6.GetPostsException>>.value(
                      _FakeResult<_i5.Posts, _i6.GetPostsException>()))
          as _i4.Future<_i2.Result<_i5.Posts, _i6.GetPostsException>>);
}
